/**
 * WASM type re-exports
 *
 * These types are generated by wasm-bindgen and re-exported for convenience.
 * In production, these would be imported from the actual WASM package.
 *
 * @module wasm-types
 */

/**
 * Cache configuration for WASM
 */
export interface CacheConfig {
  maxSize: number;
  ttlSeconds: number;
}

/**
 * Model task types
 */
export enum ModelTaskWasm {
  PromptInjection = 0,
  Toxicity = 1,
  Sentiment = 2,
}

/**
 * Model variant types
 */
export enum ModelVariantWasm {
  FP16 = 0,
  FP32 = 1,
  INT8 = 2,
}

/**
 * Cache statistics from WASM
 */
export interface CacheStatsWasm {
  hits: number;
  misses: number;
  totalRequests(): number;
  hitRate(): number;
  toJson(): string;
}

/**
 * ML configuration for WASM
 */
export interface MLConfigWasm {
  enabled: boolean;
  threshold: number;
  fallbackToHeuristic: boolean;
  cacheEnabled: boolean;
  toJson(): string;
}

/**
 * Placeholder for WASM module initialization
 *
 * In production, this would be the actual wasm-bindgen init function
 */
export async function initWasm(): Promise<void> {
  // TODO: Call actual WASM init
  return Promise.resolve();
}
